<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Users_group_model extends CI_Model
{

    public $table = 'users_group';
    public $id = 'id_group';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    function remove_menu($id)
    {
      $this->db->where('id_menu_link',$id);
      return $this->db->delete('scm_menu_link');
    }

    function created_menu($data)
    {
      return $this->db->insert('scm_menu_link',$data);
    }
    // get all
    function get_all_menu()
    {
        $this->db->select('*');
        $this->db->from('scm_menu_link');
        $this->db->join('users_group', 'users_group.id_group = scm_menu_link.id_group', 'left');
        $this->db->order_by('id_menu_link','DESC');
        return $this->db->get()->result();
    }

    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_group', $q);
	$this->db->or_like('form_access', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_group', $q);
	$this->db->or_like('form_access', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Users_group_model.php */
/* Location: ./application/models/Users_group_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-05 17:04:22 */
/* http://harviacode.com */
